# Generated by Django 5.0.2 on 2024-03-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ishop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50, null=True)),
                ("address", models.CharField(default="", max_length=150, null=True)),
                ("mobile", models.BigIntegerField(default=1)),
                ("pincode", models.BigIntegerField(default=0)),
                ("city", models.CharField(default="", max_length=50, null=True)),
                (
                    "address_type",
                    models.CharField(default="", max_length=100, null=True),
                ),
                ("price", models.IntegerField(default=1)),
                ("quantity", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ishop.registration",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ishop.product"
                    ),
                ),
            ],
        ),
    ]
