# Generated by Django 5.0.2 on 2024-03-21 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ishop", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pincode",
        ),
    ]
