# Generated by Django 5.0.2 on 2024-03-21 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ishop", "0003_remove_order_address_type_remove_order_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
    ]
